site_name: Make Lötstation - Makerspace Repair-Café Hilpoltstein
site_url: https://makes-hacks-hip.github.io/MakeLoetstation/
nav:
    - Repair-Café: https://www.repaircafe-hilpoltstein.de
    - Makerspace: https://makes-hacks-hip.de
    - Makerspace@Github: https://makes-hacks-hip.github.io
theme: readthedocs
repo_url: https://github.com/makes-hacks-hip/makeloetstation/
edit_uri: edit/main/docs/
